class DegreeSkills(object):
    
    degree_skills = {"software developer" :{
        "computer science": {"memory": 2, "compilers": 2, "c": 2, "java": 2, "test design": 2, "algorithms": 5, "math": 5, "statistics": 3, "sw_general": 5},
        "mechanical engineering" : {"math": 3, "statistics": 1, "sw_general": 2},
        "electrical engineering" : {"c": 1, "algorithms": 3, "math": 5, "statistics": 3, "sw_general": 2},
        "business": {"math": 1, "statistics": 1, "sw_general": 1},
        "information": {},
        "marketing": {},
        "logistics": {},
        "math": {},
        "physics" : {},
        "biology": {},
        "statistics": {},
        "finance": {},
        "architecture": {},
        "art": {},
        "design": {},
        "music": {},
        "media": {},
        "psychology": {},
        "accounting": {},
        "human resources" : {},
        "engineering": {},
        "technology": {},
        "law": {},
        "health": {}
    },
    "hardware developer" :{
        "computer science": {},
        "mechanical engineering" : {},
        "electrical engineering" : {},
        "business": {},
        "information": {},
        "marketing": {},
        "logistics": {},
        "math": {},
        "physics" : {},
        "biology": {},
        "statistics": {},
        "finance": {},
        "architecture": {},
        "art": {},
        "design": {},
        "music": {},
        "media": {},
        "psychology": {},
        "accounting": {},
        "human resources" : {},
        "engineering": {},
        "technology": {},
        "law": {},
        "health": {}
    },
    "analytics" :{
        "computer science": {},
        "mechanical engineering" : {},
        "electrical engineering" : {},
        "business": {},
        "information": {},
        "marketing": {},
        "logistics": {},
        "math": {},
        "physics" : {},
        "biology": {},
        "statistics": {},
        "finance": {},
        "architecture": {},
        "art": {},
        "design": {},
        "music": {},
        "media": {},
        "psychology": {},
        "accounting": {},
        "human resources" : {},
        "engineering": {},
        "technology": {},
        "law": {},
        "health": {}
    },
    "design" :{
        "computer science": {},
        "mechanical engineering" : {},
        "electrical engineering" : {},
        "business": {},
        "information": {},
        "marketing": {},
        "logistics": {},
        "math": {},
        "physics" : {},
        "biology": {},
        "statistics": {},
        "finance": {},
        "architecture": {},
        "art": {},
        "design": {},
        "music": {},
        "media": {},
        "psychology": {},
        "accounting": {},
        "human resources" : {},
        "engineering": {},
        "technology": {},
        "law": {},
        "health": {}
    },
    "marketing" :{
        "computer science": {},
        "mechanical engineering" : {},
        "electrical engineering" : {},
        "business": {},
        "information": {},
        "marketing": {},
        "logistics": {},
        "math": {},
        "physics" : {},
        "biology": {},
        "statistics": {},
        "finance": {},
        "architecture": {},
        "art": {},
        "design": {},
        "music": {},
        "media": {},
        "psychology": {},
        "accounting": {},
        "human resources" : {},
        "engineering": {},
        "technology": {},
        "law": {},
        "health": {}
    },
    "finance" :{
        "computer science": {},
        "mechanical engineering" : {},
        "electrical engineering" : {},
        "business": {},
        "information": {},
        "marketing": {},
        "logistics": {},
        "math": {},
        "physics" : {},
        "biology": {},
        "statistics": {},
        "finance": {},
        "architecture": {},
        "art": {},
        "design": {},
        "music": {},
        "media": {},
        "psychology": {},
        "accounting": {},
        "human resources" : {},
        "engineering": {},
        "technology": {},
        "law": {},
        "health": {}
    },
  
    }


    def __init__(self):
        # degree - bechelor, master, phd, associate
        # degree subject - result from degree_binning
        self.degree = degree
        self.degree_subject = degree_subject

    def return_skills(self):
        for d in self.degree_bins.keys():
            if self.degree == d:
